runtime: python311

# Variables de entorno para App Engine
env_variables:
  PHONE_IP: "https://populationless-amada-unobservedly.ngrok-free.dev"  # URL pública de ngrok
  CAPTURE_VIDEO: "True"
  CAPTURE_AUDIO: "True"
  DURATION: "5"
  BUCKET_NAME: "iot-captures-481620"
  VERTEX_AI_ENDPOINT: "https://southamerica-east1-aiplatform.googleapis.com/v1/projects/peaceful-impact-478922-t6/locations/southamerica-east1/endpoints/4530889505971896320:predict"
  VERTEX_AI_PROJECT: "peaceful-impact-478922-t6"
  FLASK_ENV: "production"

# Configuración de recursos
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Manejo de archivos estáticos (opcional)
handlers:
- url: /.*
  script: auto